version: "3.8"

services:
  nest:
    container_name: nest
    build: .
    image: nestapp:nest
    tty: true
    stdin_open: true
  # change the $(pwd) with the result of the "pwd" command
    volumes:
      - C:\Users\dmonf\OneDrive\Desktop\hackaton\app:/app